kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test -race -v ./... -cover

  - name: version
    image: node:13
    commands:
      - npx semantic-release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.132.1/goreleaser_Linux_x86_64.tar.gz | tar xzf - -C /tmp
      - /tmp/goreleaser -f "$PWD/.goreleaser.yml"
    when:
      event: tag

volumes:
  - name: deps
    temp: {}
